config/routes.rb
Rails.application.routes.draw do
  get 'carrito/carrito'

  get 'welcome/index'

  get 'welcome/politica_privacidad'

  get 'welcome/politica_devoluciones'

  get 'welcome/contactanos'
  
  devise_for :users, controllers:{registrations: "users/registrations", sessions:"users/sessions", passwords:"users/passwords"}

  resources :canciones

  resources :ventas

  resources :clientes

  resources :costumers

  resources :artistas

  resources :discos

  resources :artista

  resources :discograficas

  resources :generos
  get 'prueba/:id' =>  'generos#edit', as: :editar_genero
  
  get 'discos/generos/(:genero_id)' => 'discos#index', as: :discos_por_genero
  
  post 'canciones/agregar_carrito/:id' => 'discos#add_item_to_shipping_cart', as: :agregar_a_carrito
    
  root 'welcome#index' 









end

app/models/genero.rb
class Genero < ActiveRecord::Base
  has_many :discos
  mount_uploader :imagen, ImagenUploader
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  before_action :set_genero, only: [:show, :edit, :update, :destroy]

  # GET /generos
  # GET /generos.json
  def index
    @generos = Genero.all
  end

  # GET /generos/1
  # GET /generos/1.json
  def show
  end

  # GET /generos/new
  def new
    @genero = Genero.new
    authorize! :create, @genero
  end

  # GET /generos/1/edit
  def edit
  end

  # POST /generos
  # POST /generos.json
  def create
    @genero = Genero.new(genero_params)

    respond_to do |format|
      authorize! :create, @genero
      if @genero.save
        format.html { redirect_to @genero, notice: 'Genero was successfully created.' }
        format.json { render :show, status: :created, location: @genero }
      else
        format.html { render :new }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generos/1
  # PATCH/PUT /generos/1.json
  def update
    respond_to do |format|
      authorize! :create, @genero
      if @genero.update(genero_params)
        format.html { redirect_to @genero, notice: 'Genero was successfully updated.' }
        format.json { render :show, status: :ok, location: @genero }
      else
        format.html { render :edit }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generos/1
  # DELETE /generos/1.json
  def destroy
    authorize! :create, @genero
    @genero.destroy
    respond_to do |format|
      format.html { redirect_to generos_url, notice: 'Genero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genero
      @genero = Genero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genero_params
      params.require(:genero).permit(:nombre, :descripcion, :imagen)
    end
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/views/generos/_form.html.erb
<%= bootstrap_form_for(@genero) do |f| %>
	<%= f.alert_message "Datos incorrectos, corrija los siguientes datos:" %>
    <%= f.text_field :nombre %>
    <%= f.text_field :descripcion %>
    <%= f.file_field :imagen %>
    <%= f.submit %>
<% end %>

app/views/generos/edit.html.erb
<h1><%= title "Editar genero" %></h1>

<%= render 'form' %>

<%= link_to 'Ver', @genero %> |
<%= link_to 'Atrás', generos_path %>

app/views/generos/index.html.erb
<h1>Lista de generos</h1>

<% @generos.in_groups_of(3, false) do |gg| %>
	<div class="row">
		<% gg.each do |g| %>
			<div class="col-sm-4">
				<h3 class="text-center text-primary"><%= g.nombre %></h3>
				<%= image_tag g.imagen, class: 'img-catalogo center-block'%>
				<p class="text-center margin-10"><%= g.descripcion%></p>
				<div class="text-center">
					<%= link_to "Ver discos de este genero", discos_por_genero_path(g), class: 'btn btn-primary btn-sm' %>
					<%= link_to 'Editar', edit_genero_path(g), class: 'btn btn-default btn-sm' %>
					<%= link_to 'Borrar', g, method: :delete, data: { confirm: 'Estas seguro?' }, class: 'btn btn-danger btn-sm' %>
				</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/generos/new.html.erb
<h1><%= title "Nuevo genero" %></h1>

<%= render 'form' %>

<%= link_to 'Atras', generos_path %>

app/views/generos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @genero.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @genero.descripcion %>
</p>

<%= link_to 'Editar genero', editar_genero_path(@genero) %> |
<%= link_to 'Atrás', generos_path %>