config/routes.rb
Rails.application.routes.draw do
  get 'carrito/carrito'

  get 'welcome/index'

  get 'welcome/politica_privacidad'

  get 'welcome/politica_devoluciones'

  get 'welcome/contactanos'
  
  devise_for :users, controllers:{registrations: "users/registrations", sessions:"users/sessions", passwords:"users/passwords"}

  resources :canciones

  resources :ventas

  resources :clientes

  resources :costumers

  resources :artistas

  resources :discos

  resources :artista

  resources :discograficas

  resources :generos
  get 'prueba/:id' =>  'generos#edit', as: :editar_genero
  
  get 'discos/generos/(:genero_id)' => 'discos#index', as: :discos_por_genero
  
  post 'canciones/agregar_carrito/:id' => 'discos#add_item_to_shipping_cart', as: :agregar_a_carrito
    
  root 'welcome#index' 









end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
       
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/artista.rb
class Artista < ActiveRecord::Base
  mount_uploader :imagen, ImagenUploader
  
  has_many :discos
end

app/models/cancion.rb
class Cancion < ActiveRecord::Base
  belongs_to :disco
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/disco.rb
class Disco < ActiveRecord::Base
  belongs_to :artista
  belongs_to :discografica
  belongs_to :genero
  
  has_many :canciones
  
  ## Configurar los campos para indicar que guardaran imagenes
  mount_uploader :portada_trasera, ImagenUploader
  mount_uploader :portada_delantera, ImagenUploader
  
  def paypal_url(return_path)
    values = {
      business: "prhiroal@gmail.com",
      cmd: "_xclick",
      upload: 1,
      return: "#{Rails.application.secrets.app_host}#{return_path}",
      invoice: id,
      amount: precio,
      item_name: nombre,
      item_number: id,
      quantity: '1'
    }
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
  
  def multiple_paypal_url(return_path, total)
    values = {
      business: "prhiroal@gmail.com",
      cmd: "_xclick",
      upload: 1,
      return: "https://www.sandbox.paypal.com#{return_path}",
      invoice: 1,
      amount: total,
      item_name: "Multiple discos",
      item_number: 1,
      quantity: '1'
    }
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
end

app/models/discografica.rb
class Discografica < ActiveRecord::Base
  has_many :discos
end

app/models/genero.rb
class Genero < ActiveRecord::Base
  has_many :discos
  mount_uploader :imagen, ImagenUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/venta.rb
class Venta < ActiveRecord::Base
end

app/controllers/discos_controller.rb
class DiscosController < ApplicationController
  before_action :set_disco, only: [:show, :edit, :update, :destroy, :add_item_to_shipping_cart]

  # GET /discos
  # GET /discos.json
  def index
    @generos = Genero.all
    if params[:genero_id].nil?
      @genero = Genero.first
    else
      @genero = Genero.find_by(id: params[:genero_id])
    end
    @discos = @genero.discos.order(:nombre => :asc)
    
  end

  # GET /discos/1
  # GET /discos/1.json
  def show
    @canciones = @disco.canciones
    @duracion = @canciones.sum(:duracion)
  end

  # GET /discos/new
  def new
    @disco = Disco.new
    authorize! :create, @disco
  end

  # GET /discos/1/edit
  def edit
  end

  # POST /discos
  # POST /discos.json
  def create
    @disco = Disco.new(disco_params)

    respond_to do |format|
      authorize! :create, @disco
      if @disco.save
        DiscoMailer.new_disco(@disco).deliver
        format.html { redirect_to @disco, notice: 'Disco was successfully created.' }
        format.json { render :show, status: :created, location: @disco }
      else
        format.html { render :new }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discos/1
  # PATCH/PUT /discos/1.json
  def update
    respond_to do |format|
      authorize! :create, @disco
      if @disco.update(disco_params)
        format.html { redirect_to @disco, notice: 'Disco was successfully updated.' }
        format.json { render :show, status: :ok, location: @disco }
      else
        format.html { render :edit }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discos/1
  # DELETE /discos/1.json
  def destroy
    authorize! :create, @disco
    @disco.destroy
    respond_to do |format|
      format.html { redirect_to discos_url, notice: 'Disco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_item_to_shipping_cart
    if user_signed_in?
      if cookies[:carrito].nil?
        cookies[:carrito] = [@disco.id].to_json 
        redirect_to @disco
      else
        @item = JSON.parse(cookies[:carrito])
        @item << @disco.id
        cookies[:carrito] = @item.to_json
        redirect_to @disco
      end
    end
  end
  
  def comprar
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disco
      @disco = Disco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disco_params
      params.require(:disco).permit(:nombre, :publicacion, :precio, :artista_id, :discografica_id, :portada_delantera, :portada_trasera, :genero_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @generos = Genero.all.order(:nombre).first(6)
    @artistas = Artista.all.order(:nombre).first(12)
    @discos = Disco.all.order(:nombre).first(12)
  end

  def politica_privacidad
  end

  def politica_devoluciones
  end

  def contactanos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artista_helper.rb
module ArtistaHelper
end

app/helpers/artistas_helper.rb
module ArtistasHelper
end

app/helpers/canciones_helper.rb
module CancionesHelper
  def mostrar_duracion(segundos)
    "#{(segundos / 70).round}:#{(segundos % 60).to_s.rjust(2, '0')} min"
  end
end

app/helpers/carrito_helper.rb
module CarritoHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/discograficas_helper.rb
module DiscograficasHelper
end

app/helpers/discos_helper.rb
module DiscosHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/ventas_helper.rb
module VentasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/contactanos.html.erb
<h1>Welcome#contactanos</h1>
<p>Find me in app/views/welcome/contactanos.html.erb</p>

app/views/welcome/index.html.erb
<div class="page-header">
	<h2 class="text-primary">Géneros</h2>
	<div class="row">
		<% @generos.each do |g|%>
		<div class="col-sm-2 text-center">
			<h4><%= g.nombre  %></h4>
			<%= image_tag g.imagen, class: 'img-responsive img-catalogo' %>
		</div>
		<% end %>
	</div>
	<hr />
	<div class="text-center">
		<%= button_to "Ver más géneros", generos_path, method: :get, class: 'btn btn-primary center-block'%>
	</div>
</div>
<div class="page-header">
	<h2 class="text-primary">Artistas</h2>
	<div class="row">
		<% @artistas.each do |a|%>
		<div class="col-sm-2 text-center">
			<%= link_to a do %>
			<h4><%= a.nombre  %></h4>
				<%= image_tag a.imagen, class: 'img-responsive img-catalogo' %>
			<% end %>
		</div>
		<% end %>
	</div>
	<hr />
	<div class="text-center">
		<%= button_to "Ver más artistas", artistas_path, method: :get, class: 'btn btn-primary center-block'%>
	</div>

</div>
<div class="page-header">
	<h2 class="text-primary">Discos populares</h2>
	<%  @discos.in_groups_of(6, false) do |dg| %>
	<div class="row" style="height: 200px">

		<% dg.each do |d|%>
		<div class="col-sm-2">

			<h4 class="text-center"><%= d.nombre  %></h4>
			<div class="flip-container">
				<%= link_to d do %>
					<div class="flipper">
						<div class=" text-center front">
							<%= image_tag d.portada_delantera, class: 'img-responsive img-catalogo' %>
						</div>
						<div class="text-center back">
							<%= image_tag d.portada_trasera, class: 'img-responsive img-catalogo' %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
		<% end %>

	</div>
	<% end %>
	<div class="text-center">
		<%= button_to "Ver más discos", discos_path(), method: :get, class: 'btn btn-primary center-block'%>
	</div>
</div>

<%= button_to 'Agregar disco', new_disco_path, class: 'btn btn-primary center-block', method: :get %>

app/views/welcome/politica_devoluciones.html.erb
<h1>Política de devoluciones</h1>
<div class="container" style="min-width: 60%; max-width: 80%">
	<h2>Para productos físicos</h2>
	<p>Para realizar la devolución de un articulo comprado en Clavecromática es necesario que dicho articulo se encunetre en buenas condiciones, excepto en el caso en que llegue dañado de la paquetería.
		El artículo no podrá ser devuelto si el cliente ha modificado o dañaado el producto.
		El cliente tiene un lapso de 15 días para pedir una devolución.
		El cliente recibirá un producto igual a cambio del producto regresado, en caso que dicho producto no se encuentre en existencia el cliente podrá recibir un producto de precio similar o menor.
		El cliente pagará la tarifa de envío.
		</p>
	<h2>Para productos digitales</h2>
	<p>No se pueden hacer devoluciones sobre productos digitales adquridos a través de la tienda Clavecromática.</p>
</div>

app/views/welcome/politica_privacidad.html.erb
<h1>Poltica de privacidad</h1>
<div class="container" style="max-width: 80%; min-width: 60%">
	<h2>Datos personales que recopilamos</h2>
	<p>Para poder garantizar nuestro mejor servicio y eficacia, ClaveCromática recopila y almacena datos proporcionados directa o indirectamente por nuestros clientes. Entre los datos que recopilamos se encuentran el correo electrónico, nombre y domicilio, que son datos que usted como cliente proporciona directamente. Además registramos datos de las compras que realiza para monitorear los movimientos y llevar un registro en caso de la necesidad de una devolución.
	ClaveCromática también pudiera recopilar otra información relativa a usted, como su IP de procedencia, el tipo de navegador o el idioma. Estos datos son utilizados para ofrecer un perfil más adecuado a nuestros usuarios y generar estadísticas.
	</p>
	<h2>Como usamos sus datos personales</h2>
	<p>ClaveCromática utiliza sus datos sólo para ofrecerle un mejor servicio, no guardamos datos que no sean relevantes para nuestro servicio ni compartimos datos que nos proporcione. El correo electrónico y la contraseña son almacenados para que usted pueda autenticarse en el sistema, además de recibir si así lo desea un boletín periódico con información de nuestro servicio. Mientras que la dirección es necesaria para el servicio de paquetería.
	ClaveCromática se reserva el derecho de poder remitir por cualquier medio electrónico a sus usuarios notificaciones, avisos y/o noticias relacionadas con el servicio.
	Siempre que un usuario postee un comentario públicamente, éste estará disponible para el público en general. La ClaveCromatica no se hace responsable de la información confidencial propia publicada por un mismo usuario en el Sitio Web, siendo el usuario el único responsable de lo que publica.
	ClaveCromatica se reserva el derecho de poder realizar cambios en esta Política de Privacidad, los cuales serán publicados para que nuestros usuarios y visitantes tengan constancia de los mismos. Los usuarios del Sitio Web quedarán sujetos a la nueva Política de Privacidad cuando entren en vigor en el sitio.
	</p>
</div>