config/routes.rb
Rails.application.routes.draw do
  get 'carrito/carrito'

  get 'welcome/index'

  get 'welcome/politica_privacidad'

  get 'welcome/politica_devoluciones'

  get 'welcome/contactanos'
  
  devise_for :users, controllers:{registrations: "users/registrations", sessions:"users/sessions", passwords:"users/passwords"}

  resources :canciones

  resources :ventas

  resources :clientes

  resources :costumers

  resources :artistas

  resources :discos

  resources :artista

  resources :discograficas

  resources :generos
  get 'prueba/:id' =>  'generos#edit', as: :editar_genero
  
  get 'discos/generos/(:genero_id)' => 'discos#index', as: :discos_por_genero
  
  post 'canciones/agregar_carrito/:id' => 'discos#add_item_to_shipping_cart', as: :agregar_a_carrito
    
  root 'welcome#index' 









end

app/models/disco.rb
class Disco < ActiveRecord::Base
  belongs_to :artista
  belongs_to :discografica
  belongs_to :genero
  
  has_many :canciones
  
  ## Configurar los campos para indicar que guardaran imagenes
  mount_uploader :portada_trasera, ImagenUploader
  mount_uploader :portada_delantera, ImagenUploader
  
  def paypal_url(return_path)
    values = {
      business: "prhiroal@gmail.com",
      cmd: "_xclick",
      upload: 1,
      return: "#{Rails.application.secrets.app_host}#{return_path}",
      invoice: id,
      amount: precio,
      item_name: nombre,
      item_number: id,
      quantity: '1'
    }
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
  
  def multiple_paypal_url(return_path, total)
    values = {
      business: "prhiroal@gmail.com",
      cmd: "_xclick",
      upload: 1,
      return: "https://www.sandbox.paypal.com#{return_path}",
      invoice: 1,
      amount: total,
      item_name: "Multiple discos",
      item_number: 1,
      quantity: '1'
    }
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end
end

app/controllers/discos_controller.rb
class DiscosController < ApplicationController
  before_action :set_disco, only: [:show, :edit, :update, :destroy, :add_item_to_shipping_cart]

  # GET /discos
  # GET /discos.json
  def index
    @generos = Genero.all
    if params[:genero_id].nil?
      @genero = Genero.first
    else
      @genero = Genero.find_by(id: params[:genero_id])
    end
    @discos = @genero.discos.order(:nombre => :asc)
    
  end

  # GET /discos/1
  # GET /discos/1.json
  def show
    @canciones = @disco.canciones
    @duracion = @canciones.sum(:duracion)
  end

  # GET /discos/new
  def new
    @disco = Disco.new
    authorize! :create, @disco
  end

  # GET /discos/1/edit
  def edit
  end

  # POST /discos
  # POST /discos.json
  def create
    @disco = Disco.new(disco_params)

    respond_to do |format|
      authorize! :create, @disco
      if @disco.save
        DiscoMailer.new_disco(@disco).deliver
        format.html { redirect_to @disco, notice: 'Disco was successfully created.' }
        format.json { render :show, status: :created, location: @disco }
      else
        format.html { render :new }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discos/1
  # PATCH/PUT /discos/1.json
  def update
    respond_to do |format|
      authorize! :create, @disco
      if @disco.update(disco_params)
        format.html { redirect_to @disco, notice: 'Disco was successfully updated.' }
        format.json { render :show, status: :ok, location: @disco }
      else
        format.html { render :edit }
        format.json { render json: @disco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discos/1
  # DELETE /discos/1.json
  def destroy
    authorize! :create, @disco
    @disco.destroy
    respond_to do |format|
      format.html { redirect_to discos_url, notice: 'Disco was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_item_to_shipping_cart
    if user_signed_in?
      if cookies[:carrito].nil?
        cookies[:carrito] = [@disco.id].to_json 
        redirect_to @disco
      else
        @item = JSON.parse(cookies[:carrito])
        @item << @disco.id
        cookies[:carrito] = @item.to_json
        redirect_to @disco
      end
    end
  end
  
  def comprar
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disco
      @disco = Disco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disco_params
      params.require(:disco).permit(:nombre, :publicacion, :precio, :artista_id, :discografica_id, :portada_delantera, :portada_trasera, :genero_id)
    end
end

app/helpers/discos_helper.rb
module DiscosHelper
end

app/views/discos/_form.html.erb
<%= bootstrap_form_for(@disco) do |f| %>
    <%= f.text_field :nombre %>
    <%= f.date_select :publicacion %>
    <%= f.text_field :precio, prepend: "$", append: ".00" %>
	<%= f.select :artista_id, options_for_select(Artista.all.map {|a| [a.nombre, a.id ]})%>
	<%= f.select :genero_id, options_for_select(Genero.all.map {|g| [g.nombre, g.id ]})%>
    <%= f.select :discografica_id, options_for_select(Discografica.all.map {|d| [d.nombre, d.id ]})%>
    <%= f.file_field :portada_delantera %>
    <%= f.file_field :portada_trasera %>
	<%= f.submit %>
<% end %>

app/views/discos/edit.html.erb
<h1 class="text-primary"><%= title "Editar disco" %></h1>

<%= render 'form' %>

<%= link_to 'Ver', @disco %> |
<%= link_to 'Atras', discos_path %>

app/views/discos/index.html.erb
<h1 class="text-primary">
	Lista de discos<br />
</h1>
<div class="page-header">
	<h3>Buscar por géneros</h3>
	<ul class="nav nav-pills">
		<% @generos.each do |g| %>
			<li role="presentation" class="<%= @genero == g ? "active" : nil %>"><%= link_to g.nombre, discos_por_genero_path(g) %></li>
		<% end %>
	</ul>
</div>
<div class="page-header">
	<h3 class="text-center"><%= @genero.nombre %></h3>
	<%= image_tag @genero.imagen, class: 'portada center-block'%>
	<p class="lead"><%= @genero.descripcion %></p>
</div>
<h2 class="page-header">
	Discos del género <%= @genero.nombre %>
</h2>
<%  @discos.in_groups_of(4, false) do |dg| %>
	<div class="row" style="height: 200px">

		<% dg.each do |d|%>
		<div class="col-sm-3">

			<h4 class="text-center"><%= d.nombre  %></h4>
			<div class="flip-container flip-container-canciones center-block">
				<%= link_to d do %>
					<div class="flipper">
						<div class=" text-center front">
							<%= image_tag d.portada_delantera, class: 'img-responsive img-catalogo' %>
						</div>
						<div class="text-center back">
							<%= image_tag d.portada_trasera, class: 'img-responsive img-catalogo' %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
		<% end %>

	</div>
<% end %>

app/views/discos/new.html.erb
<h1><%= title "Nuevo disco" %></h1>

<%= render 'form' %>

<%= link_to 'Atrás', discos_path %>

app/views/discos/show.html.erb
<div class="text-center">
	<%= image_tag @disco.portada_delantera, class: 'portada' %>
	<h1><%= @disco.nombre %>
		<br /><small><%= link_to @disco.artista.nombre, @disco.artista %></small>
	</h1>
</div>
<div class="panel panel-primary">
	<div class="panel-heading"><h4>Datos del disco</h4></div>
	<div class="panel-body">
		<b>Nombre: </b><%= @disco.nombre %><br />
		<b>Discográfica: </b><%= @disco.discografica.nil? ? "Sin información" : @disco.discografica.nombre %><br />
		<b>Año de publicación: </b><%= @disco.publicacion.strftime("%d/%m/%Y")%><br />
		<b>Duración: </b><%= mostrar_duracion(@duracion) %>
	</div>
	
</div>
<div class="page-header">
	<h2>Canciones</h2>
</div>
<table class="table table-hover table-striped">
	<tr>
		<th>Canciones</th>
		<th>Artista</th>
		<th class="text-center">Duración</th>
	</tr>
	<% @canciones.each do |c| %>
		<tr>
			<td><%= c.nombre %></td>
			<td><%= link_to c.disco.artista.nombre, c.disco.artista %></td>
			<td class="text-center"><%= mostrar_duracion(c.duracion) %></td>
		</tr>
	<% end %>
</table>
<%= link_to "Comprar", @disco.paypal_url(disco_path(@disco)) %>
<% if can? :edit, @disco%>
	<%= button_to "Editar disco", edit_disco_path(@disco ), method: :get, class: 'btn btn-primary center-block'%>
<% end %>
<% if user_signed_in?%>
	<%= button_to "Agregar al carrito", agregar_a_carrito_path(@disco), method: :post, class: 'btn btn-primary center-block' %>
<% end %>